Source/MvcWebRole/Controllers/RequestStatsController.cs
using System.Web.Mvc;
using MvcWebRole.Models;
using VKStats.Queue;

namespace MvcWebRole.Controllers
{
    public class RequestStatsController : BaseController
    {
        private readonly IRequestStatsQueue requestStatsQueue;

        public RequestStatsController(IRequestStatsQueue requestStatsQueue)
        {
            this.requestStatsQueue = requestStatsQueue;
        }

        // GET: RequestStats
        public ActionResult Index()
        {
            return View(new RequestStatsViewModel());
        }

        [HttpPost]
        public ActionResult Index(RequestStatsViewModel model)
        {
            if (!ModelState.IsValid)
                return View();

            requestStatsQueue.AddItem(new RequestStatsData { WallOwnerId = UserId, VKUserScreenName = model.VKUserScreenName });
            return View("RequestStatsSuccess", new RequestStatsResultViewModel { Private = UserId != 0 });
        }
    }
}

Source/MvcWebRole/Controllers/WallController.cs
using System.Linq;
using System.Web.Mvc;
using MvcWebRole.Models;
using VKStats.Domain.Repository;

namespace MvcWebRole.Controllers
{
    [Authorize]
    public class WallController : BaseController
    {
        public const int DefaultRecordsCount = 10;
        private readonly IRepositoryFactory repositoryFactory;

        public WallController(IRepositoryFactory repositoryFactory)
        {
            this.repositoryFactory = repositoryFactory;
        }

        public ActionResult Index()
        {
            var wallRepository = repositoryFactory.GetWallRepository(UserId);
            var startFrom = wallRepository.GetTopId(UserId);

            return View(new WallViewModel { WallOwnerId = UserId, StartFrom = startFrom, Count = DefaultRecordsCount });
        }

        [ChildActionOnly, AllowAnonymous]
        [OutputCache(Duration = 600, VaryByParam = "*")]
        public ActionResult WallList(int wallOwnerId, int startFrom, int count)
        {
            var wallRepository = repositoryFactory.GetWallRepository(0);

            var records = wallRepository.GetTopRecords(wallOwnerId, startFrom, count).ToList();
            var last = records.LastOrDefault();

            var model = new WallListViewModel { Records = records, LastPostId = last != null ? last.Id : 0 };

            return View(model);
        }

        public ActionResult WallPartial(int startFrom)
        {
            return View("_WallPartial", new WallViewModel { WallOwnerId = UserId, StartFrom = startFrom - 1, Count = WallController.DefaultRecordsCount });
        }
    }
}

Source/MvcWebRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - VKStats</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("VKStats", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i>&nbsp;Home</a></li>
                    <li><a href="@Url.Action("Index", "Wall")"><i class="fa fa-user"></i>&nbsp;My Wall</a></li>
                    <li><a href="@Url.Action("Index", "RequestStats")"><i class="fa fa-plus"></i>&nbsp;New Request</a></li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - VKStats</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery", "~/bundles/bootstrap", "~/bundles/site")
    @RenderSection("scripts", required: false)
</body>
</html>

Source/MvcWebRole/Views/Shared/_WallContainer.cshtml
@model MvcWebRole.Models.WallViewModel
@{
    Layout = null;
}

<div id="wallContainer">
    @Html.Partial("_WallPartial")
</div>
<div id="bottomLoading" class="collapse"><i class="fa fa-spinner"></i>&nbsp;Loading...</div>
<div id="noMorePosts" class="collapse"><i class="fa fa-info-circle"></i>&nbsp;No more posts.</div>

Source/MvcWebRole/Views/Shared/_WallPartial.cshtml
@model MvcWebRole.Models.WallViewModel
@{
    Layout = null;
}

@Html.Action("WallList", "Wall", new { wallOwnerId = Model.WallOwnerId, startFrom = Model.StartFrom, count = Model.Count })